# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee86e243cf8eaaf64bfe8a2fbfebaab0db92cf76be23cd5b8a70eff794c557d41759b4739b4853e7c8450ddb0a2e3995a64da4721b4c2c700eb1281db3ad2ce

test:
  secret_key_base: 1e02625b2ba7b3d3ca549fd78ad5b0216b7b5028aded6416d539985ffa17e6c635242f964ba08dc057c4bcbc51728384a822ff1871048bd8ecbdb8e4549fc314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
